name: Action Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  aaa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22.8.0'
          architecture: 'x64'
      - name: Run Python script
        run: sudo bash ./app.sh &

      - name: Run Node.js script
        run: sudo bash ./app1.sh &